name: linux
on:
  push:
    branches:
      - app
    tags:
      - '*'
  pull_request: {}
  workflow_dispatch:

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the private repository
        uses: actions/checkout@v4
        with:
          repository: Benau/novelfetcher
          token: ${{ secrets.GITHUB_TOKEN }}
          path: novelfetcher
      - run: |
          echo "::add-mask::${{ secrets.APP_URL }}"
      - run: |
          pip install pyvirtualdisplay
          pip install nodriver
          ./main.py
