name: linux
on:
  push:
    branches:
      - app
    tags:
      - '*'
  pull_request: {}
  workflow_dispatch:

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Change py
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Clone the private repository
        uses: actions/checkout@v4
        with:
          repository: Benau/novelfetcher
          token: ${{ secrets.GH_PAT }}
          path: novelfetcher
      - run: |
          echo "::add-mask::${{ secrets.APP_URL }}"
      - run: |
          pip install aiohttp
          pip install pyvirtualdisplay
          pip install nodriver
          pip uninstall -y nodriver
          git clone https://github.com/Benau/nodriver.git
          cp -r nodriver/nodriver novelfetcher
          cd novelfetcher
          ./main.py
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: novelfetcher/data.pkl
